server:
  port: 8085
  context-path: /SpringBootCRUDApp
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize:  10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect:  org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
dataSource:
  sampleapp:
    url:  jdbc:mysql://@localhost:3306/ricky
    username: root
    passowrd: ricky
    driverClassName:  com.mysql.jdbc.Driver
    defaultSchema:  
    maxPoolSize:  20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect:  org.hibernate.dialect.MySQLDialect
 